# Generated by Django 5.2.14 on 2026-06-11 04:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('extension', models.CharField(default='.py', max_length=20)),
                ('lines_of_code', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('security', 'Security'), ('bug', 'Bug'), ('code_quality', 'Code Quality'), ('performance', 'Performance'), ('style', 'Style'), ('complexity', 'Complexity'), ('testing', 'Testing')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('column_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('tool_name', models.CharField(choices=[('custom_rule', 'Custom Rule'), ('bandit', 'Bandit'), ('ruff', 'Ruff'), ('pylint', 'Pylint'), ('radon', 'Radon'), ('ai', 'AI Reviewer')], default='custom_rule', max_length=50)),
                ('rule_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='accounts.codefile')),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('original_code', models.TextField(blank=True, null=True)),
                ('fixed_code', models.TextField(blank=True, null=True)),
                ('patch_diff', models.TextField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='accounts.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_type', models.CharField(choices=[('zip', 'ZIP Upload'), ('github', 'GitHub Repository'), ('single_file', 'Single Python File')], default='zip', max_length=20)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='project_zips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('github_url', models.URLField(blank=True, null=True)),
                ('extracted_path', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(default='Python', max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('total_python_files', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='codefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_files', to='accounts.project'),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files_scanned', models.IntegerField(default=0)),
                ('total_issues_found', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('high_issues', models.IntegerField(default=0)),
                ('medium_issues', models.IntegerField(default=0)),
                ('low_issues', models.IntegerField(default=0)),
                ('security_score', models.FloatField(default=100)),
                ('code_quality_score', models.FloatField(default=100)),
                ('maintainability_score', models.FloatField(default=100)),
                ('overall_score', models.FloatField(default=100)),
                ('scan_log', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='scan_reports/')),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_fixed', models.IntegerField(default=0)),
                ('total_pending', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=100)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='accounts.scan')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.scan'),
        ),
    ]
